// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum TopicBitmapItemOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct TopicBitmapItem<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for TopicBitmapItem<'a> {
  type Inner = TopicBitmapItem<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> TopicBitmapItem<'a> {
  pub const VT_KEY: flatbuffers::VOffsetT = 4;
  pub const VT_BITMAP: flatbuffers::VOffsetT = 6;

  pub const fn get_fully_qualified_name() -> &'static str {
    "TopicBitmapItem"
  }

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    TopicBitmapItem { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args TopicBitmapItemArgs<'args>
  ) -> flatbuffers::WIPOffset<TopicBitmapItem<'bldr>> {
    let mut builder = TopicBitmapItemBuilder::new(_fbb);
    if let Some(x) = args.bitmap { builder.add_bitmap(x); }
    if let Some(x) = args.key { builder.add_key(x); }
    builder.finish()
  }


  #[inline]
  pub fn key(&self) -> Option<&'a B256> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<B256>(TopicBitmapItem::VT_KEY, None)}
  }
  #[inline]
  pub fn bitmap(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(TopicBitmapItem::VT_BITMAP, None)}
  }
}

impl flatbuffers::Verifiable for TopicBitmapItem<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<B256>("key", Self::VT_KEY, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("bitmap", Self::VT_BITMAP, false)?
     .finish();
    Ok(())
  }
}
pub struct TopicBitmapItemArgs<'a> {
    pub key: Option<&'a B256>,
    pub bitmap: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for TopicBitmapItemArgs<'a> {
  #[inline]
  fn default() -> Self {
    TopicBitmapItemArgs {
      key: None,
      bitmap: None,
    }
  }
}

pub struct TopicBitmapItemBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> TopicBitmapItemBuilder<'a, 'b> {
  #[inline]
  pub fn add_key(&mut self, key: &B256) {
    self.fbb_.push_slot_always::<&B256>(TopicBitmapItem::VT_KEY, key);
  }
  #[inline]
  pub fn add_bitmap(&mut self, bitmap: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TopicBitmapItem::VT_BITMAP, bitmap);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> TopicBitmapItemBuilder<'a, 'b> {
    let start = _fbb.start_table();
    TopicBitmapItemBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<TopicBitmapItem<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for TopicBitmapItem<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("TopicBitmapItem");
      ds.field("key", &self.key());
      ds.field("bitmap", &self.bitmap());
      ds.finish()
  }
}
