// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum WithdrawalOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Withdrawal<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Withdrawal<'a> {
  type Inner = Withdrawal<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Withdrawal<'a> {
  pub const VT_INDEX: flatbuffers::VOffsetT = 4;
  pub const VT_VALIDATOR_INDEX: flatbuffers::VOffsetT = 6;
  pub const VT_ADDRESS: flatbuffers::VOffsetT = 8;
  pub const VT_AMOUNT: flatbuffers::VOffsetT = 10;

  pub const fn get_fully_qualified_name() -> &'static str {
    "Withdrawal"
  }

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Withdrawal { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args WithdrawalArgs<'args>
  ) -> flatbuffers::WIPOffset<Withdrawal<'bldr>> {
    let mut builder = WithdrawalBuilder::new(_fbb);
    builder.add_validator_index(args.validator_index);
    builder.add_index(args.index);
    if let Some(x) = args.amount { builder.add_amount(x); }
    if let Some(x) = args.address { builder.add_address(x); }
    builder.finish()
  }


  #[inline]
  pub fn index(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Withdrawal::VT_INDEX, Some(0)).unwrap()}
  }
  #[inline]
  pub fn validator_index(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Withdrawal::VT_VALIDATOR_INDEX, Some(0)).unwrap()}
  }
  #[inline]
  pub fn address(&self) -> Option<&'a Address> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Address>(Withdrawal::VT_ADDRESS, None)}
  }
  #[inline]
  pub fn amount(&self) -> Option<&'a U256> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<U256>(Withdrawal::VT_AMOUNT, None)}
  }
}

impl flatbuffers::Verifiable for Withdrawal<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("index", Self::VT_INDEX, false)?
     .visit_field::<u64>("validator_index", Self::VT_VALIDATOR_INDEX, false)?
     .visit_field::<Address>("address", Self::VT_ADDRESS, false)?
     .visit_field::<U256>("amount", Self::VT_AMOUNT, false)?
     .finish();
    Ok(())
  }
}
pub struct WithdrawalArgs<'a> {
    pub index: u64,
    pub validator_index: u64,
    pub address: Option<&'a Address>,
    pub amount: Option<&'a U256>,
}
impl<'a> Default for WithdrawalArgs<'a> {
  #[inline]
  fn default() -> Self {
    WithdrawalArgs {
      index: 0,
      validator_index: 0,
      address: None,
      amount: None,
    }
  }
}

pub struct WithdrawalBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> WithdrawalBuilder<'a, 'b> {
  #[inline]
  pub fn add_index(&mut self, index: u64) {
    self.fbb_.push_slot::<u64>(Withdrawal::VT_INDEX, index, 0);
  }
  #[inline]
  pub fn add_validator_index(&mut self, validator_index: u64) {
    self.fbb_.push_slot::<u64>(Withdrawal::VT_VALIDATOR_INDEX, validator_index, 0);
  }
  #[inline]
  pub fn add_address(&mut self, address: &Address) {
    self.fbb_.push_slot_always::<&Address>(Withdrawal::VT_ADDRESS, address);
  }
  #[inline]
  pub fn add_amount(&mut self, amount: &U256) {
    self.fbb_.push_slot_always::<&U256>(Withdrawal::VT_AMOUNT, amount);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> WithdrawalBuilder<'a, 'b> {
    let start = _fbb.start_table();
    WithdrawalBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Withdrawal<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Withdrawal<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Withdrawal");
      ds.field("index", &self.index());
      ds.field("validator_index", &self.validator_index());
      ds.field("address", &self.address());
      ds.field("amount", &self.amount());
      ds.finish()
  }
}
