// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum BlockHeaderSegmentOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct BlockHeaderSegment<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for BlockHeaderSegment<'a> {
  type Inner = BlockHeaderSegment<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> BlockHeaderSegment<'a> {
  pub const VT_FIRST_BLOCK_NUMBER: flatbuffers::VOffsetT = 4;
  pub const VT_HEADERS: flatbuffers::VOffsetT = 6;

  pub const fn get_fully_qualified_name() -> &'static str {
    "BlockHeaderSegment"
  }

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    BlockHeaderSegment { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args BlockHeaderSegmentArgs<'args>
  ) -> flatbuffers::WIPOffset<BlockHeaderSegment<'bldr>> {
    let mut builder = BlockHeaderSegmentBuilder::new(_fbb);
    builder.add_first_block_number(args.first_block_number);
    if let Some(x) = args.headers { builder.add_headers(x); }
    builder.finish()
  }


  #[inline]
  pub fn first_block_number(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(BlockHeaderSegment::VT_FIRST_BLOCK_NUMBER, Some(0)).unwrap()}
  }
  #[inline]
  pub fn headers(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<BlockHeader<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<BlockHeader>>>>(BlockHeaderSegment::VT_HEADERS, None)}
  }
}

impl flatbuffers::Verifiable for BlockHeaderSegment<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("first_block_number", Self::VT_FIRST_BLOCK_NUMBER, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<BlockHeader>>>>("headers", Self::VT_HEADERS, false)?
     .finish();
    Ok(())
  }
}
pub struct BlockHeaderSegmentArgs<'a> {
    pub first_block_number: u64,
    pub headers: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<BlockHeader<'a>>>>>,
}
impl<'a> Default for BlockHeaderSegmentArgs<'a> {
  #[inline]
  fn default() -> Self {
    BlockHeaderSegmentArgs {
      first_block_number: 0,
      headers: None,
    }
  }
}

pub struct BlockHeaderSegmentBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> BlockHeaderSegmentBuilder<'a, 'b> {
  #[inline]
  pub fn add_first_block_number(&mut self, first_block_number: u64) {
    self.fbb_.push_slot::<u64>(BlockHeaderSegment::VT_FIRST_BLOCK_NUMBER, first_block_number, 0);
  }
  #[inline]
  pub fn add_headers(&mut self, headers: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<BlockHeader<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(BlockHeaderSegment::VT_HEADERS, headers);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> BlockHeaderSegmentBuilder<'a, 'b> {
    let start = _fbb.start_table();
    BlockHeaderSegmentBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<BlockHeaderSegment<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for BlockHeaderSegment<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("BlockHeaderSegment");
      ds.field("first_block_number", &self.first_block_number());
      ds.field("headers", &self.headers());
      ds.finish()
  }
}
