// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::cmp::Ordering;
use core::mem;
pub enum BlockLogsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct BlockLogs<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for BlockLogs<'a> {
    type Inner = BlockLogs<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table::new(buf, loc),
        }
    }
}

impl<'a> BlockLogs<'a> {
    pub const VT_BLOCK_NUMBER: flatbuffers::VOffsetT = 4;
    pub const VT_LOGS: flatbuffers::VOffsetT = 6;

    pub const fn get_fully_qualified_name() -> &'static str {
        "BlockLogs"
    }

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        BlockLogs { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args BlockLogsArgs<'args>,
    ) -> flatbuffers::WIPOffset<BlockLogs<'bldr>> {
        let mut builder = BlockLogsBuilder::new(_fbb);
        builder.add_block_number(args.block_number);
        if let Some(x) = args.logs {
            builder.add_logs(x);
        }
        builder.finish()
    }

    #[inline]
    pub fn block_number(&self) -> u64 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<u64>(BlockLogs::VT_BLOCK_NUMBER, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn logs(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Log<'a>>>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Log>>,
            >>(BlockLogs::VT_LOGS, None)
        }
    }
}

impl flatbuffers::Verifiable for BlockLogs<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
            .visit_field::<u64>("block_number", Self::VT_BLOCK_NUMBER, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Log>>,
            >>("logs", Self::VT_LOGS, false)?
            .finish();
        Ok(())
    }
}
pub struct BlockLogsArgs<'a> {
    pub block_number: u64,
    pub logs: Option<
        flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Log<'a>>>>,
    >,
}
impl<'a> Default for BlockLogsArgs<'a> {
    #[inline]
    fn default() -> Self {
        BlockLogsArgs {
            block_number: 0,
            logs: None,
        }
    }
}

pub struct BlockLogsBuilder<'a: 'b, 'b> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> BlockLogsBuilder<'a, 'b> {
    #[inline]
    pub fn add_block_number(&mut self, block_number: u64) {
        self.fbb_
            .push_slot::<u64>(BlockLogs::VT_BLOCK_NUMBER, block_number, 0);
    }
    #[inline]
    pub fn add_logs(
        &mut self,
        logs: flatbuffers::WIPOffset<
            flatbuffers::Vector<'b, flatbuffers::ForwardsUOffset<Log<'b>>>,
        >,
    ) {
        self.fbb_
            .push_slot_always::<flatbuffers::WIPOffset<_>>(BlockLogs::VT_LOGS, logs);
    }
    #[inline]
    pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> BlockLogsBuilder<'a, 'b> {
        let start = _fbb.start_table();
        BlockLogsBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> flatbuffers::WIPOffset<BlockLogs<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for BlockLogs<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("BlockLogs");
        ds.field("block_number", &self.block_number());
        ds.field("logs", &self.logs());
        ds.finish()
    }
}
