// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::cmp::Ordering;
use core::mem;
pub enum SegmentGroupOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SegmentGroup<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for SegmentGroup<'a> {
    type Inner = SegmentGroup<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table::new(buf, loc),
        }
    }
}

impl<'a> SegmentGroup<'a> {
    pub const VT_FIRST_BLOCK_NUMBER: flatbuffers::VOffsetT = 4;
    pub const VT_SEGMENT_SIZE: flatbuffers::VOffsetT = 6;
    pub const VT_SEGMENT_COUNT: flatbuffers::VOffsetT = 8;
    pub const VT_LOG_BY_ADDRESS: flatbuffers::VOffsetT = 10;
    pub const VT_LOG_BY_TOPIC: flatbuffers::VOffsetT = 12;

    pub const fn get_fully_qualified_name() -> &'static str {
        "SegmentGroup"
    }

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        SegmentGroup { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args SegmentGroupArgs<'args>,
    ) -> flatbuffers::WIPOffset<SegmentGroup<'bldr>> {
        let mut builder = SegmentGroupBuilder::new(_fbb);
        builder.add_first_block_number(args.first_block_number);
        if let Some(x) = args.log_by_topic {
            builder.add_log_by_topic(x);
        }
        if let Some(x) = args.log_by_address {
            builder.add_log_by_address(x);
        }
        builder.add_segment_count(args.segment_count);
        builder.add_segment_size(args.segment_size);
        builder.finish()
    }

    #[inline]
    pub fn first_block_number(&self) -> u64 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<u64>(SegmentGroup::VT_FIRST_BLOCK_NUMBER, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn segment_size(&self) -> u32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<u32>(SegmentGroup::VT_SEGMENT_SIZE, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn segment_count(&self) -> u32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<u32>(SegmentGroup::VT_SEGMENT_COUNT, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn log_by_address(
        &self,
    ) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<AddressBitmapItem<'a>>>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<AddressBitmapItem>>,
            >>(SegmentGroup::VT_LOG_BY_ADDRESS, None)
        }
    }
    #[inline]
    pub fn log_by_topic(
        &self,
    ) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<TopicBitmapItem<'a>>>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<TopicBitmapItem>>,
            >>(SegmentGroup::VT_LOG_BY_TOPIC, None)
        }
    }
}

impl flatbuffers::Verifiable for SegmentGroup<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
            .visit_field::<u64>("first_block_number", Self::VT_FIRST_BLOCK_NUMBER, false)?
            .visit_field::<u32>("segment_size", Self::VT_SEGMENT_SIZE, false)?
            .visit_field::<u32>("segment_count", Self::VT_SEGMENT_COUNT, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<AddressBitmapItem>>,
            >>("log_by_address", Self::VT_LOG_BY_ADDRESS, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<TopicBitmapItem>>,
            >>("log_by_topic", Self::VT_LOG_BY_TOPIC, false)?
            .finish();
        Ok(())
    }
}
pub struct SegmentGroupArgs<'a> {
    pub first_block_number: u64,
    pub segment_size: u32,
    pub segment_count: u32,
    pub log_by_address: Option<
        flatbuffers::WIPOffset<
            flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<AddressBitmapItem<'a>>>,
        >,
    >,
    pub log_by_topic: Option<
        flatbuffers::WIPOffset<
            flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<TopicBitmapItem<'a>>>,
        >,
    >,
}
impl<'a> Default for SegmentGroupArgs<'a> {
    #[inline]
    fn default() -> Self {
        SegmentGroupArgs {
            first_block_number: 0,
            segment_size: 0,
            segment_count: 0,
            log_by_address: None,
            log_by_topic: None,
        }
    }
}

pub struct SegmentGroupBuilder<'a: 'b, 'b> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> SegmentGroupBuilder<'a, 'b> {
    #[inline]
    pub fn add_first_block_number(&mut self, first_block_number: u64) {
        self.fbb_
            .push_slot::<u64>(SegmentGroup::VT_FIRST_BLOCK_NUMBER, first_block_number, 0);
    }
    #[inline]
    pub fn add_segment_size(&mut self, segment_size: u32) {
        self.fbb_
            .push_slot::<u32>(SegmentGroup::VT_SEGMENT_SIZE, segment_size, 0);
    }
    #[inline]
    pub fn add_segment_count(&mut self, segment_count: u32) {
        self.fbb_
            .push_slot::<u32>(SegmentGroup::VT_SEGMENT_COUNT, segment_count, 0);
    }
    #[inline]
    pub fn add_log_by_address(
        &mut self,
        log_by_address: flatbuffers::WIPOffset<
            flatbuffers::Vector<'b, flatbuffers::ForwardsUOffset<AddressBitmapItem<'b>>>,
        >,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            SegmentGroup::VT_LOG_BY_ADDRESS,
            log_by_address,
        );
    }
    #[inline]
    pub fn add_log_by_topic(
        &mut self,
        log_by_topic: flatbuffers::WIPOffset<
            flatbuffers::Vector<'b, flatbuffers::ForwardsUOffset<TopicBitmapItem<'b>>>,
        >,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            SegmentGroup::VT_LOG_BY_TOPIC,
            log_by_topic,
        );
    }
    #[inline]
    pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> SegmentGroupBuilder<'a, 'b> {
        let start = _fbb.start_table();
        SegmentGroupBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> flatbuffers::WIPOffset<SegmentGroup<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for SegmentGroup<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("SegmentGroup");
        ds.field("first_block_number", &self.first_block_number());
        ds.field("segment_size", &self.segment_size());
        ds.field("segment_count", &self.segment_count());
        ds.field("log_by_address", &self.log_by_address());
        ds.field("log_by_topic", &self.log_by_topic());
        ds.finish()
    }
}
