// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::cmp::Ordering;
use core::mem;
// struct U128, aligned to 1
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct U128(pub [u8; 16]);
impl Default for U128 {
    fn default() -> Self {
        Self([0; 16])
    }
}
impl core::fmt::Debug for U128 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("U128")
            .field("value", &self.value())
            .finish()
    }
}

impl flatbuffers::SimpleToVerifyInSlice for U128 {}
impl<'a> flatbuffers::Follow<'a> for U128 {
    type Inner = &'a U128;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        <&'a U128>::follow(buf, loc)
    }
}
impl<'a> flatbuffers::Follow<'a> for &'a U128 {
    type Inner = &'a U128;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        flatbuffers::follow_cast_ref::<U128>(buf, loc)
    }
}
impl<'b> flatbuffers::Push for U128 {
    type Output = U128;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = ::core::slice::from_raw_parts(self as *const U128 as *const u8, Self::size());
        dst.copy_from_slice(src);
    }
}

impl<'a> flatbuffers::Verifiable for U128 {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.in_buffer::<Self>(pos)
    }
}

impl<'a> U128 {
    #[allow(clippy::too_many_arguments)]
    pub fn new(value: &[u8; 16]) -> Self {
        let mut s = Self([0; 16]);
        s.set_value(value);
        s
    }

    pub const fn get_fully_qualified_name() -> &'static str {
        "U128"
    }

    pub fn value(&'a self) -> flatbuffers::Array<'a, u8, 16> {
        // Safety:
        // Created from a valid Table for this object
        // Which contains a valid array in this slot
        unsafe { flatbuffers::Array::follow(&self.0, 0) }
    }

    pub fn set_value(&mut self, items: &[u8; 16]) {
        // Safety:
        // Created from a valid Table for this object
        // Which contains a valid array in this slot
        unsafe { flatbuffers::emplace_scalar_array(&mut self.0, 0, items) };
    }
}
