name: Build all crates

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      target:
        required: false
        type: string
        default: "all-crates"
      artifact_name:
        required: false
        type: string
        default: ""
    secrets:
      cachix-token:
        required: true

jobs:
  build:
    name: "Build ${{ inputs.target }}"
    runs-on: "${{ inputs.os }}"
    steps:
      - name: Set $USER if needed
        run: |
          if [ -z "$USER" ]; then
            echo "USER=runner" >> "$GITHUB_ENV"
          fi
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - uses: cachix/cachix-action@v15
        with:
          name: apibara-public
          authToken: "${{ secrets.cachix-token }}"
      - run: nix build .#${{ inputs.target }} -L --accept-flake-config
      - uses: actions/upload-artifact@v4
        if: ${{ inputs.artifact_name != '' }}
        with:
          name: ${{ inputs.artifact_name }}
          path: result/*
