name: CI Pipeline

on:
  push:
    branches: ["backport"]

jobs:
  check:
    name: "Checks"
    uses: ./.github/workflows/ci-check.yml
    with:
      os: warp-ubuntu-latest-x64-4x
    secrets:
      cachix-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"

  build-linux-x86_64:
    needs: check
    name: "Linux x86_64: Build"
    uses: ./.github/workflows/build.yml
    with:
      os: warp-ubuntu-latest-x64-4x
    secrets:
      cachix-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"

  build-macos-aarch64:
    needs: check
    name: "MacOS aarch64: Build"
    uses: ./.github/workflows/build.yml
    with:
      os: warp-macos-latest-arm64-6x
    secrets:
      cachix-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
