name: CI Pipeline

on:
  push:
    branches: ["backport-sink"]

jobs:
  check:
    name: "Checks"
    uses: ./.github/workflows/ci-check.yml
    with:
      os: ubuntu-latest
    secrets:
      cachix-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"

  build-linux-x86_64:
    needs: check
    name: "Linux x86_64: Build"
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-latest
    secrets:
      cachix-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"

  build-macos-aarch64:
    needs: check
    name: "MacOS aarch64: Build"
    uses: ./.github/workflows/build.yml
    with:
      os: macos-latest
    secrets:
      cachix-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
